name: build carbon
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/setup-python
      - name: get python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # https://github.com/marketplace/actions/setup-bazelisk
      - name: install bazelisk
        uses: bazelbuild/setup-bazelisk@v2
      - name: install llvm
        # Must be Homebrew; GitHub Action's LLVM install doesn't work :/
        run: brew install llvm
      - name: build lol
        run: |
          bazel build //explorer
          ls
          ls bazel-bin || true
          ls bazel-bin/explorer || true
          ls bazel-bin/explorer/explorer || true
      - name: upload built file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: explorer
          path: bazel-bin/explorer/explorer
